Корутины
AlinaPirajoke/UniversityMobileProject pull request #4
Opened 2023-11-21 16:43 UTC by AlinaPirajoke

Добавил **корутин** в места обращения к бд.
Остальное по мелочи (бд перелопатил, новый экран реализовал)

2023-11-24 09:22 UTC, P3ndalf reviewed
приложи сразу фотку с новым экраном или скинь мне в личку записанный видос с приложением

2023-11-24 11:00 UTC, P3ndalf commented on app/src/main/java/com/example/university/Model/AppDB/AppDbHelper.kt
> +
лишняя строчка

2023-11-24 11:01 UTC, P3ndalf commented on app/src/main/java/com/example/university/Model/AppDB/AppDbManager.kt
> +
пустая строчка лишняя

2023-11-24 11:02 UTC, P3ndalf commented on app/src/main/java/com/example/university/Model/AppDB/AppDbManager.kt
> +            Log.e(TAG, "Мы проебали id для слова $word")
понял

2023-11-24 11:21 UTC, P3ndalf commented on app/src/main/java/com/example/university/View/Auth/Screens/RegistrationView.kt
>      // Мня за такие аргументы не опустят?
удали коммент и удали лишние строчки 55,56,57

2023-11-24 11:21 UTC, P3ndalf commented on app/src/main/java/com/example/university/View/Auth/Screens/RegistrationView.kt
> +    if (uiState.isGoingToMain){
отформатируй файл

2023-11-24 11:30 UTC, P3ndalf commented on app/src/main/java/com/example/university/View/Main/Screens/AddView.kt
> +                context.lifecycleScope.launch { vm.addWord() }
не, не так. если у тебя какая-то асинхронная работа должна выполняться на уровне @Composable, то ты используешь это след образом:
1) создаешь переменную вначале функции: `val scope = rememberCoroutineScope()`
2) создаешь корутину в коде: `scope.launch { ... }`
В твоем случае, тебе надо здесь просто вызывать vm.addWord(), а уже в телефункции во вьюмодели пишешь след образом: `viewModelScope.launch { withContext(Dispatchers.IO) { .... } }`

2023-11-24 11:30 UTC, P3ndalf commented on app/src/main/java/com/example/university/View/Main/Screens/AddView.kt
> +    context: MainActivity,
так делать нельзя

2023-11-24 11:31 UTC, P3ndalf commented on app/src/main/java/com/example/university/View/Main/Screens/AddView.kt
> +    context: MainActivity,
чтобы достать контекст можно использовать нативную функцию в компоузе: `LocalContext.current`

2023-11-24 11:32 UTC, P3ndalf commented on app/src/main/java/com/example/university/View/Main/Screens/AddView.kt
> +    context: MainActivity,
`
@Composable
fun OnLifecycleEventCompose(
    lifecycleOwner: LifecycleOwner,
    onStart: (() -> Unit)? = null,
    onStop: (() -> Unit)? = null,
    onCreate: (() -> Unit)? = null,
    onResume: (() -> Unit)? = null
) {
    DisposableEffect(lifecycleOwner) {
        val observer = LifecycleEventObserver { _, event ->
            when (event) {
                Lifecycle.Event.ON_START -> {
                    onStart?.invoke()
                }
                Lifecycle.Event.ON_STOP -> {
                    onStop?.invoke()
                }
                Lifecycle.Event.ON_CREATE -> {
                    onCreate?.invoke()
                }
                Lifecycle.Event.ON_RESUME -> {
                    onResume?.invoke()
                }
                else -> {
                    Timber.d("other lifecycle event")
                }
            }
        }

        // Add the observer to the lifecycle
        lifecycleOwner.lifecycle.addObserver(observer)

        // When the effect leaves the Composition, remove the observer
        onDispose {
            lifecycleOwner.lifecycle.removeObserver(observer)
        }
    }
}
`

2023-11-24 11:32 UTC, P3ndalf commented on app/src/main/java/com/example/university/View/Main/Screens/AddView.kt
> +    context: MainActivity,
`
@Composable
fun OnLifecycleEventCompose(
    lifecycleOwner: LifecycleOwner,
    onStart: (() -> Unit)? = null,
    onStop: (() -> Unit)? = null,
    onCreate: (() -> Unit)? = null,
    onResume: (() -> Unit)? = null
) {
    DisposableEffect(lifecycleOwner) {
        val observer = LifecycleEventObserver { _, event ->
            when (event) {
                Lifecycle.Event.ON_START -> {
                    onStart?.invoke()
                }
                Lifecycle.Event.ON_STOP -> {
                    onStop?.invoke()
                }
                Lifecycle.Event.ON_CREATE -> {
                    onCreate?.invoke()
                }
                Lifecycle.Event.ON_RESUME -> {
                    onResume?.invoke()
                }
                else -> {
                    Timber.d("other lifecycle event")
                }
            }
        }

        // Add the observer to the lifecycle
        lifecycleOwner.lifecycle.addObserver(observer)

        // When the effect leaves the Composition, remove the observer
        onDispose {
            lifecycleOwner.lifecycle.removeObserver(observer)
        }
    }
}
`

2023-11-24 11:33 UTC, P3ndalf commented on app/src/main/java/com/example/university/View/Main/Screens/AddView.kt
> +    context: MainActivity,
```
@Composable
fun OnLifecycleEventCompose(
    lifecycleOwner: LifecycleOwner,
    onStart: (() -> Unit)? = null,
    onStop: (() -> Unit)? = null,
    onCreate: (() -> Unit)? = null,
    onResume: (() -> Unit)? = null
) {
    DisposableEffect(lifecycleOwner) {
        val observer = LifecycleEventObserver { _, event ->
            when (event) {
                Lifecycle.Event.ON_START -> {
                    onStart?.invoke()
                }
                Lifecycle.Event.ON_STOP -> {
                    onStop?.invoke()
                }
                Lifecycle.Event.ON_CREATE -> {
                    onCreate?.invoke()
                }
                Lifecycle.Event.ON_RESUME -> {
                    onResume?.invoke()
                }
                else -> {
                    Timber.d("other lifecycle event")
                }
            }
        }

        // Add the observer to the lifecycle
        lifecycleOwner.lifecycle.addObserver(observer)

        // When the effect leaves the Composition, remove the observer
        onDispose {
            lifecycleOwner.lifecycle.removeObserver(observer)
        }
    }
}
```

2023-11-24 11:33 UTC, P3ndalf commented on app/src/main/java/com/example/university/View/Main/Screens/AddView.kt
> +    context: MainActivity,
это если тебе потребуется вызывать действия на конкретных колбеках активности

2023-11-27 12:56 UTC, AlinaPirajoke commented on app/src/main/java/com/example/university/View/Main/Screens/AddView.kt
> +                context.lifecycleScope.launch { vm.addWord() }
А как быть если нужно получить результат?

2023-11-27 16:54 UTC, P3ndalf commented on app/src/main/java/com/example/university/Model/WordsDB/WordsDbHelper.kt
> +class WordsDbHelper {
если он не нужен - удаляй. Принцип Yagni декларирует не создавать функционал, который не будет использован

2023-11-27 16:54 UTC, P3ndalf commented on app/src/main/java/com/example/university/Model/WordsDB/WordsDbNames.kt
> +
лишняя строчка

2023-11-27 16:55 UTC, P3ndalf commented on app/src/main/java/com/example/university/UsefullStuff/Word.kt
> +class Word(
data class

2023-11-27 16:56 UTC, P3ndalf commented on app/src/main/java/com/example/university/UsefullStuff/Word.kt
> +    fun translationsToString(): String{
сделай это как kotlin extension, чтобы не нарушать логику data-классов
`fun Word.translationToString()`. И вообще ты можешь переопределить дефолтный метод toString(), чтобы не плодить методы

2023-11-27 16:57 UTC, P3ndalf commented on app/src/main/java/com/example/university/View/Auth/Screens/RegistrationView.kt
> +    context: AuthActivity, navController: NavHostController, vm: RegistrationViewModel = koinViewModel()
конеткст передавать не надо

2023-11-27 16:57 UTC, P3ndalf commented on app/src/main/java/com/example/university/View/Auth/Screens/RegistrationView.kt
> +    context: AuthActivity, navController: NavHostController, vm: RegistrationViewModel = koinViewModel()
LocalContext.current

2023-11-27 16:59 UTC, P3ndalf commented on app/src/main/java/com/example/university/View/Auth/Screens/RegistrationView.kt
> +            context.lifecycleScope.launch {
просто вызывай vm.addUser() а уже во вьюмодели создавай корутину. Потому что в андроиде есть некоторая разница между: viewModelScope, CoroutineScope, GlobalScope, lifecycleScope

2023-11-27 16:59 UTC, P3ndalf commented on app/src/main/java/com/example/university/View/Auth/Screens/RegistrationView.kt
> +        },
запятая лишняя

2023-11-27 17:02 UTC, P3ndalf commented on app/src/main/java/com/example/university/View/Main/Screens/AddView.kt
> +                context.lifecycleScope.launch { vm.addWord() }
создавай значение, оборачивай его в StateFlow и меняй или есть еще вариант, использовать `async` вместо `launch`: https://kotlinlang.org/api/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines/-deferred/

2023-11-27 17:04 UTC, P3ndalf commented on app/src/main/java/com/example/university/View/Main/Screens/PickQuantityView.kt
> +    context: MainActivity,
не нада

2023-11-27 17:04 UTC, P3ndalf commented on app/src/main/java/com/example/university/View/Main/Screens/PickQuantityView.kt
> +    context: MainActivity,
ДЯДЯ НЕ НАДА

2023-11-27 17:07 UTC, P3ndalf requested changes
правим

2023-11-27 20:57 UTC, AlinaPirajoke commented on app/src/main/java/com/example/university/Model/WordsDB/WordsDbHelper.kt
> +class WordsDbHelper {
Он нужен... будет

2023-11-27 21:00 UTC, AlinaPirajoke commented on app/src/main/java/com/example/university/View/Main/Screens/PickQuantityView.kt
> +    context: MainActivity,
😢 я больше так не буду 😭

2023-12-01 10:58 UTC, P3ndalf commented on app/src/main/java/com/example/university/Model/WordsDB/WordsDbNames.kt
> +
@AlinaPirajoke

2023-12-01 11:14 UTC, P3ndalf commented on app/src/main/java/com/example/university/View/Main/Screens/AddView.kt
> +
Лишняя пустая

2023-12-01 11:15 UTC, P3ndalf commented on app/src/main/java/com/example/university/View/Main/Screens/PickQuantityView.kt
> +//                .height(120.dp)
это еще надо?

2023-12-01 11:15 UTC, P3ndalf commented on app/src/main/java/com/example/university/View/Main/Screens/PickQuantityView.kt
> +                    text = "Выбранные слова:",
в стринг ресурсы

2023-12-01 11:17 UTC, P3ndalf commented on app/src/main/java/com/example/university/View/Main/Screens/TestView.kt
> +    vm.testStart(listId)
нене, так нельзя вызывать. Иначе этот метод будет вызываться каждый раз, когда меняются параметры функции.
Если надо разово вызвать то используй
```
LaunchedEffect(key1 = listId){
    vm.testStart(listId)
}
```

2023-12-01 11:20 UTC, P3ndalf commented on app/src/main/java/com/example/university/View/Main/Screens/TestView.kt
> +    vm: TestViewModel,
по идеям правильного state hoisting. Надо вынести все методы вьюмодели в коллбеки и удалить вьюмодель из параметра.
```
@Composable fun TestScreen(
    navController: NavHostController,
    state: UiState
    onExitAlert: () -> Unit,
)
```

2023-12-01 12:14 UTC, P3ndalf commented on app/src/main/java/com/example/university/View/Main/Screens/TestView.kt
> +// Колхоз? Тема?
та не, это нормально. Но для лучшей наглядности можешь добавить прогресс бар сверху экрана, который будет заполняться в зависимости от пройденного этапа, на свое усмотрение
![image](https://github.com/AlinaPirajoke/UniversityMobileProject/assets/52200518/2cd8252d-6848-4c77-98e9-060a655c9a9a)

2023-12-01 12:16 UTC, P3ndalf commented on app/src/main/java/com/example/university/View/Main/Screens/TestView.kt
> +        text = { Text("Вы действительно хотите закончить тестирование (его можно будеть продолжить позже)") },
в текстовые ресурсы выноси, а потом: stringResource(R.string.screenname_textname)

2023-12-03 10:47 UTC, AlinaPirajoke commented on app/src/main/java/com/example/university/Model/WordsDB/WordsDbNames.kt
> +
Исправил

2023-12-04 15:32 UTC, merged